### ISSUE TITLE
UI Styles : how to ?

### ISSUE THREAD

**Issue by Antoine-C** [abhinav2004/PhoneManager#2]
Hi @abhinav2004 

I've never worked with react material before so I'm wondering what guidelines you want to follow for the global styles of the app ?

Either create a object per component with its styles and doing inline style ([Like the documentation mentions](http://www.material-ui.com/#/customization/styles)) or going with a stylesheet with !important keyword ?

**Comment by abhinav2004** [comment]
I was thinking of inline styling just like the document says for every UI component. But I haven't given much thought about it right now. What do you think? I would really like to avoid !important though.

BTW which OS are you using?

**Comment by Antoine-C** [comment]
Hi

I agree with you, !important feels like a dirty hack. I'm good with inline styling for each UI Component at least everything is scoped.

I'm currently using Windows 10.

BTW : Could you add me to the contributors of PhoneManager ? So I could avoid asking for a pull request each time I want to push some commits.

Thank's !

**Comment by abhinav2004** [comment]
Ok so it works in Windows 10?

Added you as a contributor.

**Comment by Antoine-C** [comment]
Yep, I had some problems with npm but I fixed it using yarn instead
